### ISSUE TITLE
'Spin' object has no attribute 'spinor'

### ISSUE THREAD

**Issue by fran96r** [dipc-cc/hubbard#104]
Hi!

While running any example I'm getting

AttributeError: 'Spin' object has no attribute 'spinor'

I guess it has something to do with the installation. Any idea how to solve it?
Thanks.

**Comment by sofiasanz** [comment]
Hi, can you tell me which version of `sisl` do you have?

**Comment by fran96r** [comment]
The latest one, sisl v0.11.0

**Comment by sofiasanz** [comment]
Yes but in between versions the `sisl` repository has several minor changes that are stored in different commits. Maybe you have a version of this repository that you need to upgrade. Can you run these lines and show me the result?

```python
>>> import sisl
>>> print(sisl.__git_revision__)
```

**Comment by zerothi** [comment]
I think the problem is that the spinor stuff was added after the 0.11.0 release. Just try and upgrade the sisl installation (using the development version: https://zerothi.github.io/sisl/docs/latest/installation.html#development-version)

**Comment by fran96r** [comment]
Okey, now is working properly.

Thanks!

**Comment by PG13s** [comment]
Hi, I'm also facing this 'Spin' object has no attribute 'spinor' problem, the link of development version sisl is 404 now, could you give me the new link, thank you a lot! @zerothi

**Comment by zerothi** [comment]
> Hi, I'm also facing this 'Spin' object has no attribute 'spinor' problem, the link of development version sisl is 404 now, could you give me the new link, thank you a lot! @zerothi

Thanks, link updated.

**Comment by PG13s** [comment]
Thank you, it works!
