### ISSUE TITLE
 Change master branch name to main

### ISSUE THREAD

**Issue by tfrederiksen** [dipc-cc/hubbard#108]
Following https://github.com/zerothi/sisl/issues/391 I think we should also rename `master` to `main`. See instructions at https://github.com/github/renaming.

**Comment by sofiasanz** [comment]
Done!

**Comment by sofiasanz** [comment]
To change the local clone, you can update it by running the following commands:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
