### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by PG13s** [dipc-cc/hubbard#110]
Dear authors:
I use "python3 setup.py install" to install dipc-cc/hubbard but it fails.
and I get 3 warnings:
SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools. 
EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
PkgResourcesDeprecationWarning: 4.0.0-unsupported is an invalid version and will not be supported in a future release
and a error:
AttributeError: 'tuple' object has no attribute 'split'

then I use "pip install ." in installation path but also get error:
AttributeError: 'tuple' object has no attribute 'split'
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

How can i solve this installation problem？
Thank you！

**Comment by tfrederiksen** [comment]
@PG13s, can you provide some more details about your system environment (python/sisl versions etc)?

@zerothi , is this failure related to #111 ?

**Comment by zerothi** [comment]
It shouldn't be, but perhaps building with `pip -vvv` to get more output that can be debugged?

**Comment by PG13s** [comment]
centos7 linux, my python version is 3.8.3 and
Requirement already satisfied: sisl in /home/anaconda3/lib/python3.8/site-packages (0.11.0)
Requirement already satisfied: setuptools in /home/anaconda3/lib/python3.8/site-packages (from sisl) (60.2.0)
Requirement already satisfied: numpy>=1.13 in /home/anaconda3/lib/python3.8/site-packages (from sisl) (1.18.5)
Requirement already satisfied: pyparsing>=1.5.7 in /home/anaconda3/lib/python3.8/site-packages (from sisl) (2.4.7)
Requirement already satisfied: scipy in /home/anaconda3/lib/python3.8/site-packages (from sisl) (1.5.0)
Requirement already satisfied: netCDF4 in /home/anaconda3/lib/python3.8/site-packages (from sisl) (1.5.8)
Requirement already satisfied: cftime in /home/anaconda3/lib/python3.8/site-packages (from netCDF4->sisl) (1.5.1.1)

**Comment by PG13s** [comment]
Thanks for your reply, I update python version to 3.9.7 and hubbard get installed successfully.

**Comment by tfrederiksen** [comment]
Great you found a solution! I'll then close this issue.
