### ISSUE TITLE
Feature request: symmetric range as default in hubbard.plot.SpinPolarization

### ISSUE THREAD

**Issue by NikFriedrich** [dipc-cc/hubbard#117]
In plot.py `GeometryPlot.__orbitals__` the code does not default to a symmetric colorscale, like in `__realspace__`. It would be very helpful to add this check.

**Comment by sofiasanz** [comment]
Hi @NikFriedrich thanks for the suggestion! I think this symmetric colorscale makes only sense for the cases of `SpinPolarization` and `ChargeDifference` plots, which I can easily add. I think is a good idea, what do you think @tfrederiksen?

**Comment by tfrederiksen** [comment]
Sounds good to me!

**Comment by sofiasanz** [comment]
Done!

**Comment by sofiasanz** [comment]
I'll close this issue then :)
