### ISSUE TITLE
How to generate the molecular geometry in .xv format?

### ISSUE THREAD

**Issue by lidonglin12** [dipc-cc/hubbard#129]
How to generate the molecular geometry in .xv format?

**Comment by tfrederiksen** [comment]
One possibility is to build your geometry with `sisl`, then you can export it in one of the many available formats, `geom.write('molecule.XV)`, `geom.write('molecule.xyx)`, etc.

You can also convert between different formats from the command line, eg. `sgeom input.xyz output.XV`.

Note that the `.XV` format (native to SIESTA) is just one way to feed a geometry to `hubbard`, but you can do it in many other ways.

**Comment by lidonglin12** [comment]
Thank you very much. I will try it.

**Comment by lidonglin12** [comment]
> One possibility is to build your geometry with `sisl`, then you can export it in one of the many available formats, `geom.write('molecule.XV)`, `geom.write('molecule.xyx)`, etc.
> 
> You can also convert between different formats from the command line, eg. `sgeom input.xyz output.XV`.
> 
> Note that the `.XV` format (native to SIESTA) is just one way to feed a geometry to `hubbard`, but you can do it in many other ways.

Thank you very much. I will try it.

**Comment by tfrederiksen** [comment]
You're welcome. I'll close the issue for now.
