### ISSUE TITLE
'PulayMixer' object has no attribute 'clear'

### ISSUE THREAD

**Issue by yuanzhangyu** [dipc-cc/hubbard#130]
Hello,Thanks for reading my question.

When I commute some of the example molecules, anthracenes and clar-goble, I will have an error like this:

Traceback (most recent call last):
File "xxx/hubbard/examples/molecules/clar-goblet/compute_FM-AFM.py", line 25, in <module>
    mixer.clear()
 AttributeError: 'PulayMixer' object has no attribute 'clear'

But for benzene or kondo paper, it was fine. 

Could you please tell me some information about this error? 

I use MacOs, python 3.10.8, sisl 0.12.2.
Requirement already satisfied: scipy>=0.18   (from sisl) (1.9.1)
Requirement already satisfied: netCDF4  (1.6.2)
Requirement already satisfied: numpy>=1.13  (from sisl) (1.21.5)
Requirement already satisfied: pyparsing>=1.5.7  (from sisl) (3.0.9)
Requirement already satisfied: cftime  (from netCDF4->sisl) (1.6.2)

**Comment by sofiasanz** [comment]
Hi, thank you very much for your question. This problem comes from an update in [`sisl`](https://github.com/zerothi/sisl) that came after building this example script. I have updated this script and now it should work. Can you update your local repo and run it again? Thanks!!

**Comment by yuanzhangyu** [comment]
Hi, now is OK. Thanks very much for your prompt reply!
This issue can be closed!

**Comment by yuanzhangyu** [comment]
Sorry, I just ran the anthracenes example, seems it has a same problem.

Traceback (most recent call last):
  File "...hubbard/examples/molecules/anthracenes/compute.py", line 31, in <module>
    mixer.clear()
AttributeError: 'PulayMixer' object has no attribute 'clear'

Now the clar-goblet example is ok.

**Comment by sofiasanz** [comment]
Thanks! I have updated all examples scripts in commit 1e1105350c9d053f44bcbc39222eb431ba8be090. You should be able to run them fine.

**Comment by sofiasanz** [comment]
Can we close this issue now?

**Comment by yuanzhangyu** [comment]
OK, many thanks!
This issue can be closed now.

Sofia Sanz Wuhl ***@***.***>于2022年12月28日 周三21:25写道：
