### ISSUE TITLE
Calculating open structures

### ISSUE THREAD

**Issue by mlorenznano** [dipc-cc/hubbard#91]
Hello,

I wanted to calculate the transmission of doped 7AGNR. So I changed a few lines in the example code. I played a little bit around with different things and a few questions appeared:

- If I change the dopant from nitrogen to boron I see no change in the transmission function. Is this to be expected or did I do a mistake?
- If I switch from singulet to triplet state I also get the same transmission. Shouldn't there be at least a difference between the output for the up and down spin. 
- When I tried to run a calculatation with s1, s2 and s3 unequal to zero I got an error message: 

```
 Traceback (most recent call last):
 
   File "/home/lorenz/Desktop/2N-7AGNRopen.py", line 91, in <module>
     MFH_HC.converge(density.dm, tol=1e-5, mixer=mixer)
 
   File "/home/lorenz/.local/lib/python3.8/site-packages/hubbard/hamiltonian.py", line 542, in converge
     dn = self.iterate(dm_method, mixer=mixer, **func_args)
 
   File "/home/lorenz/.local/lib/python3.8/site-packages/hubbard/hamiltonian.py", line 477, in iterate
     ddm = ni - self.dm
 
 ValueError: operands could not be broadcast together with shapes (2,154) (3,154) 
```

Because unfortunately I know next to nothing about NEGF, the results could be expected butI rather asked you for advice :) 
Let me know if I you need help understanding my code.

[2N-7AGNRopen.txt](https://github.com/dipc-cc/hubbard/files/6420094/2N-7AGNRopen.txt)

**Comment by sofiasanz** [comment]
Shall we close this issue?

**Comment by mlorenznano** [comment]
Yes we can close it
