### ISSUE TITLE
Zak-phase of pristine AGNR

### ISSUE THREAD

**Issue by mlorenznano** [dipc-cc/hubbard#93]
Hi everybody,

I tried to calculate the Zak-phase for pristine w-AGNR with w = (5,7,9,...) but somehow got weird results. I created the geometry with 

`agnr = sisl.geom.agnr(w)`  let the system converge and calculated the Zak-phase with 

`Zak = H.get_Zak_phase()` I also tried 
`Zak_VB = H.get_Zak_phase(sub = Bandindex(Valenceband)` which produced different results than the first line. In the table below I charted the results of the Zak/pi in the second column and the expected results in the third column. ( I didn't list the Zak_VB/pi-values)

![image](https://user-images.githubusercontent.com/82454407/117785646-146b5c80-b245-11eb-9301-13f0337fb614.png)

so in the end I have two questions:

- Shouldn't the values for Zak and Zak_VB be the same or do I have the wrong Bandindex for the Valence-band?
- Why is there a discrepancy between the calculated values and the theoretical values?

As always thanks for your help :)

**Comment by mlorenznano** [comment]
Unfortunately didn't work. Should I send my code?

**Comment by tfrederiksen** [comment]
This works for me:
```python
from hubbard import HubbardHamiltonian, sp2, density
import sisl

for w in range(5, 24, 2):
    g = sisl.geom.agnr(w)
    g = g.move(-g.center())
    Hsp2 = sp2(g)
    H = HubbardHamiltonian(Hsp2, U=0)
    zak = H.get_Zak_phase()
    print(f'{w:2} {zak:5.2f}')
```

**Comment by mlorenznano** [comment]
Also works for me now. Thank you :)
