### ISSUE TITLE
Plot.BondOrder

### ISSUE THREAD

**Issue by mlorenznano** [dipc-cc/hubbard#98]
Good morning everybody :),
If I run the two lines right here 
```
BO = plot.BondOrder(H)
BO.set_xlim(-15,0)
```

I get this image 

![image](https://user-images.githubusercontent.com/82454407/119462251-cf652100-bd40-11eb-8c3b-c2f7c4f44b98.png)

I also tried to add

`BO.annotate(range(42))` but it produced the same picture

**Comment by tfrederiksen** [comment]
Thanks! I agree this does not look super nice. I guess you are trying to visualize just the bond orders around some selected atoms?

I have made a quick fix (f374171) so that you can now do:
```python
HH = HubbardHamiltonian(...)
BO = plot.BondOrder(HH, selection=range(42))
BO.savefig('plot.pdf')
```

**Comment by mlorenznano** [comment]
>  I guess you are trying to visualize just the bond orders around some selected atoms?

Yes exactly. And for bigger structures the numbers weren't readable anymore. 

I tested it with your fix and it works 👍 . Should I close the issue?

**Comment by tfrederiksen** [comment]
Yes, let's close the issue if it is solved.
